growbook/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls')),
    path('forum/',include('forum.urls')),
    path('strainbrowser/',include('strainbrowser.urls')),
    path('growlog/',include('growlog.urls')),
    path('wiki/',include('wiki.urls')),
    path('settings/',include('settings.urls')),
    path('martor/',include('martor.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
#-*- coding:utf-8 -*-
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

#app_name="main"

urlpatterns = [
    path('',views.index, name='index'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('password_reset/',views.password_reset_request,name='password_reset_request'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='main/password/password_reset_done.html'), 
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="main/password/password_reset_confirm.html"), 
         name='password_reset_confirm'),
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/password/password_reset_complete.html'), 
         name='password_reset_complete'),
         
         
    path('group/',views.group,name='group_index'),
    path('group/<int:group_id>/',views.group_manage,name='group_manage'),
    path('user/',views.user,name='user_index'),
    path('user/<int:user_id>',views.user_view,name='user_view'),
    path('manage_user/<int:user_id>/',views.user_manage,name='user_manage'),
]

user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path('profile/<int:user_id>/',views.profile,name='profile')
]

user/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _,gettext_noop as N_

# Create your models here.

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import auth
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import permission_required,login_required

# Create your views here.

def index(request):
    return HttpResponse('/user/index')

@login_required(login_url='/login/')
def profile(request,user_id):
    return HttpResponse("/user/profile/{}/".format(user_id))

user/templates/formview.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="Christian Moser">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

user/templates/login.html
{% extends "./formview.html" %}
{% load i18n %}
{% block content %}
<div class='login-form'>
    <form action="{% url 'user:login' %}" method='post'>
        {% csrf_token %}
        <input type='hidden' id='next' name='next' value="{{ next }}">
        <h1>{% translate "LOGIN" %}</h1>
        {% if error %}<span class='message-error'>{{ error }}</span>{% endif %}
        <table>
            <tr><td>{% translate "Email:" %}</td><td><input name="email" id="email" type="text"></td></tr>
            <tr><td>{% translate "Password:" %}</td><td><input name="password" id="password" type="password"></td></tr>
        </table>
        <input type='submit' value="{% translate 'Log in' %}">
    </form>
</div>
{% endblock %}

user/templates/register.html
{% extends './formview.html' %}
{% load i18n %}

{% block content %}
<form class="login-form">
    {% csrf_token %}
    <input type="hidden" name="next" id="next" value="{{ next }}">
    <h1>{% translate "Register a new account" %}</h1>
    <table>
        <tr>
            <td>{% translate "Email:" %}</td>
            <td><input type='email' name='email' id='email' value="{{ email }}" required></td>
        </tr>
        <tr>
            <td>{% translate "Username:" %}</td>
            <td><input type='text' name='username' id='username' value="{{ username }}" required></td>
        </tr>
        <tr>
            <td>{% translate "Password:" %}</td>
            <td><input type='password' name='password0' id='password0' required></td>
        </tr>
        <tr>
            <td>{% translate "Confirm Password:" %}</td>
            <td><input type='password' name='password1' id='password1' required></td>
        </tr>
        <tr>
            <td>{% translate "First Name:" %}</td>
            <td><input type='text' name='first_name' id='first_name' value="{{ first_name }}"></td>
        </tr>
        <tr>
            <td>{% translate "Last Name:" %}</td>
            <td><input type='text' name='last_name' id='last_name' value="{{ last_name }}"></td>
        </tr>
    </table>
    <input type='submit' value="{% translate 'Sign up' %}">
</form>
{% enblock %}