growbook/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls')),
    path('forum/',include('forum.urls')),
    path('strainbrowser/',include('strainbrowser.urls')),
    path('growlog/',include('growlog.urls')),
    path('wiki/',include('wiki.urls')),
    path('settings/',include('settings.urls')),
    path('martor/',include('martor.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
#-*- coding:utf-8 -*-
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

#app_name="main"

urlpatterns = [
    path('',views.index, name='index'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('password_reset/',views.password_reset_request,name='password_reset_request'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='main/password/password_reset_done.html'), 
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="main/password/password_reset_confirm.html"), 
         name='password_reset_confirm'),
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/password/password_reset_complete.html'), 
         name='password_reset_complete'),
         
         
    path('group/',views.group,name='group_index'),
    path('group/<int:group_id>/',views.group_manage,name='group_manage'),
    path('user/',views.user,name='user_index'),
    path('user/<int:user_id>',views.user_view,name='user_view'),
    path('manage_user/<int:user_id>/',views.user_manage,name='user_manage'),
]

strainbrowser/urls.py
#-*- coding:utf-8 -*-

from django.urls import path
from . import views

app_name = "strainbrowser"

urlpatterns = [
    path('',views.index,name='index'),
    path('breeder/',views.breeder,name='breeder'),
    path('breeder/<slug:breeder_key>/',views.breeder_overview,name='breeder_overview'),
    path('breeder_add/',views.breeder_add,name='breeder_add'),
    path('breeder_edit/<slug:breeder_key>',views.breeder_edit,name='breeder_edit'),
    path('breeder_delete/<slug:breeder_key>',views.breeder_delete,name='breeder_delete'),
    path('strain/<slug:breeder_key>/<slug:strain_key>',views.strain,name='strain'),
    path('strain_add/<slug:breeder_key>/',views.strain_add,name='strain_add'),
    path('strain_edit/<slug:breeder_key>/<slug:strain_key>/',views.strain_edit,name='strain_edit'),
    path('strain_delete/<slug:breeder_key>/<slug:strain_key>/',views.strain_delete,name='strain_delete'),
    path('strain_translate/<slug:breeder_key>/<slug:strain_key>/<str:language_code>/',
        views.strain_translate,name='strain_translate'),
    path('search/',views.strain_search,name='strain_search'),
    path('manage_user/',views.manage_user,name='user'),
    path('manage_user/<int:user_id>/',views.manage_user,name='manage_user'),
]

strainbrowser/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from main.functions import get_supported_languages
from main.config import get_locale

class BreederForm(forms.Form):
    primary_key = forms.IntegerField(widget=forms.HiddenInput(),
                                     required=True)
    name = forms.CharField(label=_("Breeder Name:"),
                           max_length=128,
                           required=True)
    key = forms.SlugField(label=_("Breeder Key:"),
                          max_length=64,
                          required=True)
    homepage = forms.URLField(label=_('Homepage:'),
                              max_length=512,
                              required=False)
    seedfinder = forms.URLField(label=_('Seedfinder.eu:'),
                                max_length=512,
                                required=False)
# BreederForm class
               
class DeleteBreederForm(forms.Form):
    key = forms.CharField(widget=forms.HiddenInput(),
                          max_length=64,
                          required=True)
    primary_key = forms.IntegerField(widget=forms.HiddenInput(),
                                     required=True)
    delete_breeder = forms.BooleanField(required=False,
                                        initial=False,
                                        label=_("Really delete breeder and all of his strains?"))
# DeleteBreederForm class

class StrainForm(forms.Form):
    primary_key = forms.IntegerField(widget=forms.HiddenInput(),
                                     required=True)
    breeder_key = forms.SlugField(widget=forms.HiddenInput(),
                                  max_length=64,
                                  required=True)
    name = forms.CharField(label=_('Strain Name:'),
                           max_length=128,
                           required=True)
    key = forms.SlugField(label=_('Strain Key:'),
                          max_length=64,
                          required=True)
    homepage = forms.URLField(label=_('Homepage:'),
                              max_length=512,
                              required=False)
    seedfinder = forms.URLField(label=_('Seedfinder.eu:'),
                                max_length=512,
                                required=False)
    info = forms.CharField(widget=forms.Textarea(),
                           label=_('Info:'),
                           required=False)
    description = forms.CharField(widget=forms.Textarea(),  
                                  label=_('Description'),
                                  required=False)
# StrainForm class
       
class StrainTranslationForm(forms.Form):
    breeder_key = forms.CharField(widget=forms.HiddenInput(),
                                  max_length=64,
                                  required=True)
    strain_key = forms.CharField(widget=forms.HiddenInput(),
                                 max_length=64,
                                 required=True)
    strain_id = forms.IntegerField(widget=forms.HiddenInput(),
                                   required=True)
    language = forms.CharField(widget=forms.HiddenInput(),required=True)
    homepage = forms.URLField(label=_('Homepage:'),
                                      max_length=512,
                                      required=False)
    seedfinder = forms.URLField(label=_('Seedfinder.eu'),
                                max_length=512,
                                required=False)
    info = forms.CharField(widget=forms.Textarea(),
                           label=_('Info:'),
                           required=False)
    description = forms.CharField(widget=forms.Textarea(),
                                  label=_('Description:'),
                                  required=False)
# StrainTranslationForm class

class StrainDeleteForm(forms.Form):
    breeder_key = forms.CharField(widget=forms.HiddenInput(),
                                  max_length=64,
                                  required=True)
    key = forms.CharField(widget=forms.HiddenInput(),
                          max_length=64,
                          required=True)
    delete = forms.BooleanField(label=_("Do you really want to delete that strain?"),
                                initial=False,
                                required=False)
    delete_translations = forms.BooleanField(label=_("Do you want to delete all the translations for that strain?"),
                                             initial=False,
                                             required=False)

strainbrowser/views.py
#-*- coding:utf-8 -*-
import os
from django.shortcuts import render,redirect,get_object_or_404
from django.utils.translation import gettext as _
from django.utils.text import slugify
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import permission_required,login_required
from django.core.exceptions import PermissionDenied
from django.template.loader import render_to_string
from .models import Breeder,Strain,StrainTranslation,StrainBackup
from main.models import Language
from main import config as main_config
from .config import COMPRESSION


from .functions import get_context_variables
from .forms import (
    BreederForm,
    DeleteBreederForm,
    StrainForm,
    StrainTranslationForm
)

from django.conf import settings

# Create your views here.

def index(request):
    context = {
        'title': _('GrowBook StrainBrowser'),
        'language_code':main_config.get_locale(),
        'author': 'Christian Moser',
        'head_title': _('GrowBook: StrainBrowser'),
        'head_description': _('StrainBrowser Home'),
        'breeder_count': Breeder.objects.all().count(),
        'strain_count': Strain.objects.all().count(),
        'url_breeder_home': reverse('strainbrowser:breeder'),
        'url_breeder_add': reverse('strainbrowser:breeder_add'),
    }
    context.update(get_context_variables(request.user))
    
    return render(request,'strainbrowser/index/index.html',context)
    
def breeder(request):
    context = {
        'title': _("GrowBook Breeders"),
        'language_code':main_config.get_locale(),
        'author': 'Christian Moser',
        'head_title': _('GrowBook: Breeders'),
        'head_description': _('Breeder list'),
        'breeder_list': Breeder.objects.filter(pk__gt = 0).order_by('name'),
    }
    context.update(get_context_variables(request.user))
    
    for breeder in context['breeder_list']:
        breeder.strain_count = breeder.strain_set.all().count()
        if context['user_breeder_edit']:
            breeder.user_edit = True
        elif request.user and request.user.is_authenticated():
            breeder.user_edit = (breeder.added_by.id == user.id)
        else:
            breeder.user_edit = False
    
    return render(request,'strainbrowser/breeder/breeder.html',context)
# breeder()
  
def breeder_overview(request,breeder_key):
    breeder = get_object_or_404(Breeder,key=breeder_key)
    locale = main_config.get_locale()
    context = {
        'language_code': locale,
        'author': "Christian Moser",
        'title': breeder.name,
        'head_title':_("GrowBook: {breeder}").format(breeder=breeder.name),
        'head_description':_("GrowBook - Breeder overview - {breeder}").format(breeder=breeder.name),
        'breeder': breeder,
        'strain_list': breeder.strain_set.all().order_by('name'),
    }
    context.update(get_context_variables(request.user))
    if request.user.is_authenticated:
        if (request.user.has_perm('strainbrowser.breeder.edit') 
                or breeder.added_by.id == request.user.id):
            breeder.user_edit = True
        else:
            breeder.user_edit = False
            
        for strain in context['strain_list']:
            if (request.user.has_perm('strainbrowser.strain.edit') 
                    or strain.added_by.id == request.user.id):
                strain.user_edit = True
            else:
                strain.user_edit = False
                
            strain.user_translate = False
            
            if locale != 'en-US':
                try:
                    translation = strain.straintranslation_set.get(language__locale=locale)
                except StrainTranslation.DoesNotExist:
                    translation = None
                    
                if request.user.has_perm('strainbrowser.strain.translate') or not translation:
                    strain.user_translate = True
        # endfor strain
        
    return render(request,'strainbrowser/breeder/breeder_overview.html',context)
# breeder_overview()


@permission_required('strainbrowser.breeder.add',login_url='/login/')
def breeder_add(request):
    html_template='strainbrowser/breeder/breeder_edit.html'
    context = {
        'language_code': main_config.get_locale(),
        'author': "Christian Moser",
        'title': _('Add a new Breeder'),
        'head_title': _("GrowBook: Breeder Add"),
        'head_description': _('Add a new Breeder'),
        'error_messages' : [],
        'submit_button': _('Add Breeder')
    }
    context.update(get_context_variables(request.user))
    
    data = {
        'primary_key': 0,        
    }

    form = None
    if request.method == 'POST':
        form = BreederForm(request.POST,data)
        context['form'] = form
        if not form.is_valid():
            return form.render(template_name=html_template,context=context)
        
        cdata = form.cleaned_data
        try:
            Breeder.objects.get(name=cdata['name'])
            context['error_messages'].append(
                _('A Breeder with name "{breeder_name}" already exists!').format(breeder_name=cdata['name']))
        except Breeder.DoesNotExist:
            pass
            
        try:
            Breeder.objects.get(key=cdata['key'])
            context['error_messages'].append(
                _('Breeder key "{breeder_key}" is already in use').format(breeder_key=cdata['key']))
        except Breeder.DoesNotExist:
            pass
            
        if context['error_messages']:
            return render(request,html_template,context)
            
        try:
            breeder = Breeder.objects.create(key=cdata['key'],
                                             name=cdata['name'],
                                             homepage=cdata['homepage'],
                                             seedfinder=cdata['seedfinder'],
                                             added_by=request.user,
                                             edited_by=request.user)
            return redirect(reverse('strainbrowser:breeder_overview', args=(breeder.key,)))
        except Exception as error:
            context['error_messages'].append(_("Unable to add breeder to database! ({})".format(error)))
        
    if not form:
        form = BreederForm(data)
        context['form'] = form
        print(context['form'])
    return render(request,html_template,context)
# breeder_add()

@login_required(login_url='/login/')
def breeder_edit(request,breeder_key):
    breeder = get_object_or_404(Breeder,key=breeder_key)
    
    if not request.user.has_perm('strainbrowser.breeder.edit') and breeder.added_by.id != request.user.id:
        raise PermissionDenied('You are not allowed to edit that breeder!')
    
    html_template = "strainbrowser/breeder/breeder_edit.html"
    
    context = {
        'author': "Christian Moser",
        'title': _("Edit Breeder {breeder}").format(breeder=breeder.name),
        'head_title': _("GrowBook: Edit Breeder {breeder}").format(breeder=breeder.name),
        'head_description': _("Edit breeder {breeder}").format(breeder=breeder.name),
        'error_messages': [],
        'submit_button': _("Save Breeder")
    }
    context.update(get_context_variables(request.user))
    data = {
        'primary_key': breeder.id,
        'key': breeder.key,
        'name': breeder.name,
        'homepage': breeder.homepage,
        'seedfinder': breeder.seedfinder,
    }

    form = None
    if request.method == "POST":
        form = BreederForm(request.POST,data)
        context['form'] = form
        if form.is_valid():
            if form.cleaned_data['primary_key'] != strain.id:
                context['error_messages'] = _('Illegal form! (Primary key mismatch)')
            if 'key' in form.changed_data:
                key_ok = True
                try:
                    test_breeder = Breeder.objects.get(key=form.cleaned_data['key'])
                    if test_breeder.id != breeder.id:
                        key_ok = False
                        context['error_messages'].append(
                            _("Breeder key \"{key}\" is already in use!").format(key=form.cleaned_data['key']))
                except Breeder.DoesNotExist:
                    pass
                if key_ok:
                    breeder.key = form.cleaned_data['key']
            
            if 'name' in form.changed_data:
                name_ok = True
                try:
                    test_breeder = Breeder.objects.get(name=form.cleaned_data['name'])
                    if test_breeder.id != breeder.id:
                        name_ok = False
                        context['error_messages'].append(
                            _('Breeder name \"{name}\" is already in use!').format(name=form.cleaned_data['name']))
                except Breeder.DoesNotExist:
                    pass
                if name_ok:
                    breeder.name = form.cleaned_data['name']
                        
            if 'homepage' in form.changed_data:
                breeder.homepage = form.cleaned_data['homepage']
            if 'seedfinder' in form.changed_data:
                breeder.seedfinder = form.cleaned_data['seedfinder']
                
            if context['error_messages']:
                return render(request,html_template,context)
                
            breeder.save()
            return redirect(reverse('strainbrowser:breeder_overview',args=(breeder.key,)))
    if not form:
        form = BreederForm(data)
        context['form'] = form
        
    return render(request,html_template,context)
# breeder_edit

def breeder_export(request,breeder_id):
    breeder = get_object_or_404(Breeder,key=breeder_id)
    return HttpResponse('/strainbrowser/breeder_export/')

def real_breeder_export(request,breeder_id):
    breeder = get_object_or_404(Breeder,key=breeder_id)
    if 'compress' in request.GET:

strainbrowser/templates/strainbrowser/breeder/breeder.html
{% extends '../main.html' %}
{% load i18n %}
{% block content %}

<div class='buttonbox'>
    {% if user_breeder_add %}
    <span class='button'>
        <a href="{% url 'strainbrowser:breeder_add' %}">{% translate "Add a breeder" %}</a>
    </span><br>
    {% endif %}
    {% if breeder.homepage %}
    <span class='button'>
        <a href="{{ breeder.homepage }}">{% translate "Breeder Homepage" %}</a>
    </span>
    {% endif %}
    {% if breeder.seedfinder %}
    <span class='button'>
        <a href="{{ breeder.seedfinder }}">{% translate "Breeder at Seedfinder.eu" %}</a>
    </span>
    {% endif %}
</div>
<div class='overview'>
    <table class='overview-table'>
        <tr>
            <th>{% translate "Breeder Name" %}</th>
            <th>{% translate "Strains" %}</th>
            <th>{% translate "Added by" %}</th>
            <th>{% translate "Actions" %}</th>
        </tr>
        {% for breeder in breeder_list %}
        <tr>
            <td><a href="{% url 'strainbrowser:breeder_overview' breeder.key %}">{{ breeder.name }}</td>
            <td>{{ breeder.strain_count }}</td>
            <td>{{ breeder.added_by.name }}</td>
            <td>
                {% if breeder.user_edit %}
                <div class='button'>
                    <a href="{% url 'strainbrowser:breeder_edit' breeder.key %}">{% translate "Edit" %}</a>
                </div>
                {% endif %}
                {% if user_breeder_delete %}
                <div class='button'>
                    <a href="{% url 'strainbrowser:breeder_delete' breeder.key %}">{% translate "Delete" %}</a>
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

strainbrowser/templates/strainbrowser/breeder/breeder_delete.html
{% extends '../main.html' %}
{% load i18n %}

{% block content %}
<p>
    <span class="message-important">You are about to delete a breeder with all 
    connected strains an translations.</span> If the some strains are already 
    connected to a growlog, the deleteion will fail!
</p>

<form class='content-form' method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <br>
    <input type='submit' value="{% translate 'Confirm Delete' %}">
</form>
{% endblock %}

strainbrowser/templates/strainbrowser/breeder/breeder_delete_done.html
{% extends "../main.html" %}
{% load i18n %}

{% block content %}
{% if delete_canceled %}
<p>{% blocktranslate %}Deleting breeder {{ breeder.name }} was canceled by user.{% endblocktranslate %}</p>
<span class="button">
    <a href="{% url 'strainbrowser:breeder_overview' breeder.key %}">{% translate "Return to breeder" %}</a>
</span>
<span class="button">
    <a href="{% url 'strainbrowser:index' %}">{% translate "Return to Strainbrowser" %}</a>
</span>
<span class="button">
    <a href="{% url 'strainbrowser:breeder' %}">{% translate "Return to breeder list" %}</a>
</span>
{% elif delete_success %}
<p>{% blocktranslate %}Breeder {{ breeder.name }} has been successfully deleted.{% endblocktranslate %}</p>
<span class="button">
    <a href="{% url 'strainbrowser:index' %}">{% translate "Return to Strainbrwoser" %}</a>
</span>
<span class="button">
    <a href="{% url 'strainbrowser:breeder' %}">{% translate "Return to breeder list" %}</a>
</span>
{% else %}
<p>{% blocktranslate %}Breeder {{ breeder.name }} could not be deleted!{% endblocktranslate %}</p>
{% if error_messages %}
<h2>Error messages</h2>
<div class="message-error">
    <ul>
{% for error in error_messages %}
        <li>{{ error }}</li>
{% endfor %}
    </ul>
</div>
{% endif %}
<span class="button">
    <a href="{% url 'strainbrowser:breeder_overview' breeder.key %}">{% translate "Return to breeder"</a>
</span>
<span class="button">
    <a href="{% url 'strainbrowser:index' %}">{% translate "Return to Strainbrowser" %}</a>
</span>
<span class="button">
    <a href="{% url 'strainbrowser:breeder' %}">{% translate "Return to Breeder list" %}</a>
</span>
{% endif %}
{% endblock %}

strainbrowser/templates/strainbrowser/breeder/breeder_edit.html
{% extends '../main.html' %}
{% load i18n %}

{% block content %}
{% if error_messages %}
<div class='message-error'>
    <ul>
    {% for error in error_messages %}
        <li>{{ error }}</span></li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<form class='content-form' method='post'>
    {% csrf_token %}
    {{ form.primary_key }}
    <table>
        {{ form.as_table }}
    </table>
    <input type='submit' value="{{ submit_button }}">
</form>
{% endblock %}

strainbrowser/templates/strainbrowser/breeder/breeder_overview.html
{% extends "../main.html" %}
{% load i18n %}
{% block content %}

<div class='buttonbox'>
    {% if breeder.homepage %}
    <span class='button'>
        <a href="{{ breeder.homepage }}">{% translate "Breeder Homepage" %}</a>
    </span>
    {% endif %}
    {% if breeder.seedfinder %}
    <span class='button'>
        <a href="{{ breeder.seedfinder }}">{% translate "Seedfinder.eu" %}</a>
    </span>
    {% endif %}

    {% if breeder.user_edit %}
    <span class='button'>
        <a href="{% url 'strainbrowser:breeder_edit' breeder.key %}">{% translate "Edit Breeder" %}</a>
    </span>
    {% endif %}
    {% if user_strain_add %}
    <span class='button'>
        <a href="{% url 'strainbrowser:strain_add' breeder.key %}">{% translate "Add a Strain" %}</a>
    </span>
    {% endif %}
</div><br>

{% if strain_list %}
<table class='overview-table'>
    <tr>
        <th>{% translate "Strain" %}</th>
        <th>{% translate "Added by" %}</th>
        <th>{% translate "Actions" %}</th>
    </tr>
    
    {% for strain in strain_list %}
    <tr>
        <td><a href="{% url 'strainbrowser:strain' breeder.key strain.key %}">{{ strain.name }}</a></td>            
        <td>{{ strain.added_by.name}} </td>
        <td>{% if strain.user_edit %}
            <span class='button'>
                <a href="{% url 'strainbrowser:strain_edit' breeder.key strain.key %}">{% translate "Edit" %}</a>
            </span>
        {% endif %} 
        {% if strain.user_translate %}
            <span class='button'>
                <a href="{% url 'strainbrowser:strain_translate' breeder.key strain.key language_code %}">
                    {% translate "Translate" %}
                </a>
            </span>
        {% endif %}
        {% if user_strain_delete %}
            <span class='button'>
                <a href="{% url 'strainbrowser:strain_delete' breeder.key strain.key %}">{% translate "Delete" %}</a>
            </span>
        {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are currently no strains for that breeder!</p>
{% endif %}
{% endblock %}