forum/urls.py
#-*- coding:utf-8 -*-

from django.urls import path
from . import views

app_name="forum"
urlpatterns = [
    path('',views.index,name='index'),
]

growbook/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls')),
    path('forum/',include('forum.urls')),
    path('strainbrowser/',include('strainbrowser.urls')),
    path('growlog/',include('growlog.urls')),
    path('wiki/',include('wiki.urls')),
    path('settings/',include('settings.urls')),
    path('martor/',include('martor.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
]

growlog/urls.py
#-*- coding:utf-8 -*-

from django.urls import path

from . import views

app_name='growlog'
urlpatterns= [
    path('',views.index,name='index'),
    path('growlog/<int:growlog_id>/',views.growlog,name='growlog'),
]

main/urls.py
#-*- coding:utf-8 -*-
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

#app_name="main"

urlpatterns = [
    path('',views.index, name='index'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('password_reset/',views.password_reset_request,name='password_reset_request'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='main/password/password_reset_done.html'), 
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="main/password/password_reset_confirm.html"), 
         name='password_reset_confirm'),
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='main/password/password_reset_complete.html'), 
         name='password_reset_complete'),
         
         
    path('group/',views.group,name='group_index'),
    path('group/<int:group_id>/',views.group_manage,name='group_manage'),
    path('user/',views.user,name='user_index'),
    path('user/<int:user_id>',views.user_view,name='user_view'),
    path('manage_user/<int:user_id>/',views.user_manage,name='user_manage'),
]

settings/urls.py
#-*- coding:utf-8 -*-

from django.urls import path
from . import views
app_name = "settings"
urlpatterns = [
    path('',views.index,name='index'),
    path('user/',views.user,name='user_settings'),
]

wiki/urls.py
from django.urls import path
from . import views

app_name='wiki'
urlpatterns = [
    path('',views.index,name='index'),
]

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib import auth
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.translation import gettext as _
from django.contrib.auth.password_validation import get_password_validators,password_validators_help_texts,validate_password
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import BadHeaderError,send_mail
from django.core.exceptions import ValidationError
from django.template.loader import render_to_string
from django.contrib.auth.decorators import permission_required
from django.urls import reverse

from .models import User
from . import config,functions

def index(request):
    language_code = config.get_locale()
    try:
        info_template = config.INFO_TEMPLATE[language_code]
    except KeyError:
        info_template = 'main/index/info.html'
        
    context = {
        'user':request.user,
        'language_code':language_code,
        'info_template':info_template,
    }
    
    context.update(functions.get_sidebar_context(request.user))
    
    if request.user.is_authenticated:
        context['title'] = _("Welcome {username} to GrowBook.org".format(username=request.user.get_full_name()))
    else:
        context['title'] = _("Welcome to GrowBook.org")
    
    return render(request,'main/index/index.html',context)

def login(request):
    context={
        'language_code':config.get_locale(),
        'topic': _('Log in'),
        'next':reverse('index'),
    }
    
    if request.method == "POST":
        try:
            email = request.POST['email'].lower()
            password = request.POST['password']
            if request.POST['next'] and url_has_allowed_host_and_scheme(request.POST['next'],allowed_hosts=[request.get_host()]):
                context['next'] = request.POST['next']
        except KeyError:
            context['error'] = _("Illegal form used!")
            return render(request,'main/login.html',context)
            
        if not email:
            context['error'] = _("No email-address given!")
            return render(request,'main/login.html',context)
        if not password:
            context['error'] = _("No password given!")
            return render(request,'main/login.html',context)
            
        user = auth.authenticate(request,username=email,password=password)
        if not user:
            context['error'] = _("Email address or password don't match!")
            return render(request,'main/login.html',context)
            
        auth.login(request,user)
        
        return redirect(context['next'])
    # Login form callback
        
    if 'next' in request.GET and url_has_allowed_host_and_scheme(request.GET['next'],allowed_hosts=[request.get_host()]):
        context['next'] = request.GET['next']
    
    return render(request,'main/login.html',context)
# login()

def logout(request):
    auth.logout(request)
    return redirect(reverse('index'))
# logout()

def signup(request):
    password_validators = get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
    context = {
        'language_code':config.get_locale(),
        'topic': _("Sign Up"),
        'email':'',
        'username':'',
        'next':reverse('index'),
        'password_validators_help': password_validators_help_texts(password_validators)
    }
    if request.method == 'POST':
        email_in_use = False
        email = request.POST['email'].lower()
        try:
            User.objects.get(email=email)
            email_in_use = True
        except User.DoesNotExist:
            context['email'] = email
            
        name_in_use = False
        try:
            User.objects.get(name=request.POST['username'])
            name_in_use = True
        except User.DoesNotExist:
            context['username'] = request.POST['username']
            
        if url_has_allowed_host_and_scheme(request.POST['next'],allowed_hosts=[request.get_host()]):
            context['next'] = request.POST['next']
        
        if email_in_use:
            context['error'] = _("Email address is already in use!")
            return render(request,'main/signup.html',context)
        if name_in_use:
            context['error'] = _("Username is already in use!")
            return render(request,'main/sginup.html',context)
        
        password0 = request.POST['password0']
        password1 = request.POST['password1']
        if password0 != password1:
            context['error'] = _("Passwords don't match!")
            return render(request,'main/signup.html',context)
        try: 
            validate_password(password0,
                              user=None,
                              password_validators=password_validators)
        except ValidationError as error:
            context['error'] = str(error)
            return render(request,'main/signup.html',context)
            
        user = User.objects.create(email=context['email'],name=context['username'])
        if user:
            user.set_password(password0)
            user.save()
            user.make_member()
        return redirect(context['next'])                
    else:
        if 'next' in request.GET and is_safe_url(request.GET['next'],allowed_hosts=[request.get_host()]):
            context['next'] = request.GET('next')
        return render(request,'main/signup.html',context)
# signup()

def password_reset_request(request):
    context = {
        'language_code': config.get_locale()
    }
    if request.method == 'POST':
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            try:
                user = User.objects.get(email=data)
                subject = "Password Reset Requested"
                try:
                    email_template = config.RESET_PASSWORD_MAIL_TEMPLATE[config.get_locale()]
                except KeyError:
                    email_template = 'main/password/password_reset_mail.txt'
                context.update({
                    'email': user.email,
                    'username': user.get_full_name(),
                    'domain': request.get_host(),
                    'site_name': 'MyGrowBook.org',
                    'user': user,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': default_token_generator.make_token(user),
                    'protocol': settings.SITE_SECURE_PROTOCOL,                    
                })
                email = render_to_string(email_template,context)
                try:
                    send_mail(subject,email,settings.EMAIL_ADDRESS_NOREPLY,[user.email])
                except BadHeaderError:
                    return HttpResponse(request,_('Invalid header found!'))
            except User.DoesNotExist:
                pass
            return redirect(reverse('password_reset_done'))
    # request.method == 'POST'
    context.update({
        'topic': _("Reset Password"),
        'password_reset_form': PasswordResetForm()
    })
    return render(request,'main/password/password_reset_request.html',context)
# password_reset_request()

@permission_required('group.manage',login_url='/login/')
def group(request):
    return HttpResponse('/group/')
# group()
    
@permission_required('group.manage',login_url='/login/')
def group_manage(request,group_id):
    return HttpResponse('/group/{}/'.format(group_id))
# group_manage()
    
@permission_required('user.manage',login_url='/login/')
def user(request):
    return HttpResponse('/user/')
# user()
    
def user_view(request,user_id):
    return HttpResponse('/user/{}/'.format(user_id))
# user_view()

@permission_required('user.manage',login_url='/login/')
def user_manage(request,user_id):
    return HttpResponse('/user/{}/'.format(user_id))
# user_manage()

templates/head.html
{% load i18n %}
{% load static %}
<head>
    <meta charset="utf-8" />
    {% if author %}
        <meta name='author' content="{{ author }}">
    {% else %}
        <meta name="author" content="Christian Moser" />
    {% endif %}

    {% if head_description %}
        <meta name="description" content="{{ head_description }}">
    {% else %}
        <meta name="description" content="{% translate 'growbook.org homepage' %}">
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    {% if head_title %}
        <title>{{ head_title }}</title>
    {% else %}
        <title>GrowBook.org</title>
    {% endif %}
</head>

templates/left_sidebar.manage.html
{% load i18n %}

{% if user_can_manage_users %}
<div class='sidebar-section'>
    <span class='sidebar-section-title'>{% translate "User Management" %}</span>
    {% if user_is_group_manager %}
    <div class='sidebar-entry'>
        <a href="{% url 'user_index' %}">{% translate "Manage Users" %}</a>
    </div>
    {% endif %}
    {% if user_is_forum_operator %}
    <div class='sidebar-entry'>
        <a href='#'>{% translate "Forum users" %}</a>
    </div>
    {% endif %}
    {% if user_is_wiki_operator %}
    <div class='sidebar-entry'>
        <a href='#'>{% translate "Wiki users" %}</a>
    </div>
    {% endif %}
    {% if user_is_strainbrowser_operator %}
    <div class='sidebar-entry'>
        <a href='#'>{% translate "StrainBrowser Users" %}</a>
    </div>
    {% endif %}
</div>
{% endif %}

{% if user_is_group_manager %}
<div class='sidebar-section'>
    <span class='sidebar-section-title'>{% translate "Group Management" %}</span>
    <div class='sidebar-entry'>
        <a href="{% url 'group_index' %}">{% translate "Manage Groups" %}</a>
    </div>
</div>
{% endif %}

templates/main.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
    {% include 'head.html' %}
    <body>
        {% include 'navbar.html' %}
        
        <div class='left-sidebar'>
            {% block left_sidebar %}
            {% endblock %}
        </div>
        
        {% if right_sidebar_enabled %}
        <div class='right-sidebar'>
            {% block right_sidebar %}
            {% endblock %}
        </div>
        {% endif %}
        
        <div class='content'>
            {% autoescape off %}
            <h1>{{ title }}</h1>
            {% endautoescape %}
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/navbar.html
{% load i18n %}
<div class='navbar'>
    <a href="{% url 'index' %}">{% translate "Home" %}</a>
    <a href="{% url 'growlog:index' %}">{% translate "Growlogs" %}</a>
    <a href="{% url 'forum:index' %}">{% translate "Forum" %}</a>
    <a href="{% url 'wiki:index' %}">{% translate "Wiki" %}</a>
    <a href="{% url 'strainbrowser:index' %}">{% translate "Strains" %}</a>
    {% if user.is_authenticated %}
        <a href="{% url 'settings:index' %}">{% translate "Settings" %}</a>
        <a href="{% url 'logout' %}">{% translate "Log Out" %}</a>
    {% else %}
        <a href="{% url 'login' %}">{% translate "Log In" %}</a>
        <a href="{% url 'signup' %}">{% translate "Sign Up" %}</a>
    {% endif %}
</div>